---
apiVersion: v1
kind: Service
metadata:
  name: test-socket
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  test_socket_mapping
      prefix: /test/
      service: test-socket
      timeout_ms: 20000
      use_websocket: true
spec:
  selector:
    app: test-socket
  ports:
  - name: first
    protocol: TCP
    port: 443
    targetPort: 8000
  - name: second
    protocol: TCP
    port: 80
    targetPort: 8000

